---
title: "Assignment 3"
author: "Edward Kim"
date: "10/13/2020"
output: github_document
---

## APIs

```{r, message = FALSE}
library(tidyverse)
library(httr)
library(xml2)
library(dplyr)
```



```{r}
#Get Number of Searchs 
website <- xml2::read_html("https://pubmed.ncbi.nlm.nih.gov/?term=sars-cov-2+trial+vaccine")
counts <- xml2::xml_find_first(website,"/html/body/main/div[9]/div[2]/div[2]/div[1]/span")
counts <- as.character(counts)
stringr::str_extract(counts,"[0-9]+")

```
There were 560 results when the term "sars-cov-2 trial vaccine" was searched on the pubmed.gov website. 

```{r}
#Get the ids
query <- httr::GET(
  url = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi",
  query = list(db = "pubmed",
               term = "sars-cov-2 trial vaccine",
               retmax = 1000
        )
)

query <- httr::content(query)
query_txt <- as.character(query)

ids <- stringr::str_extract_all(query_txt, "<Id>[0-9]+</Id>")[[1]]
ids <- stringr::str_remove_all(ids, "<Id>|</Id>")
```

```{r}
#Get all the papers that match IDs extracted
publication <- GET(
    url = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi",
    query = list( db = "pubmed",
                  id = paste(ids,collapse = ","),
                  retmx = 1000,
                  rettype = "abstract"
        )
    )

publication <- httr::content(publication)
publication_txt <- as.character(publication)
```

The content of the publication was obtained through an API that matched all of the papers with the ids that were previously generated. 

```{r one-string-per-response, eval = TRUE}
pub_char_list <- xml2::xml_children(publication)
pub_char_list <- sapply(pub_char_list, as.character)
```



```{r}
titles <- str_extract(pub_char_list, "<ArticleTitle>(\\n|.)+</ArticleTitle>")
titles <- str_remove_all(titles, "</?[[:alnum:]]+>")
titles <- str_replace_all(titles,"\\s+"," ")

journal <- str_extract_all(pub_char_list,"<Title>([:alpha:]+ ?){10}</Title>")
journal <- str_remove_all(journal, "<Title>|</Title>")

date <- str_extract_all(pub_char_list,"<PubDate>(\\n|.)+</PubDate>")
date <- str_remove_all(date, "<PubDate>|<Year>|</Year>|<Month>|</Month>|<Day>|</Day>|</PubDate>")
date <-str_remove_all(date,"\n+|<MedlineDate>|</MedlineDate>")
date <- str_replace_all(date,"\\s+"," ")


abstracts <- str_extract(pub_char_list, "<Abstract>(\\n|.)+</Abstract>")
abstracts <- str_remove_all(abstracts, "</?[[:alnum:]]+>")
abstracts <- str_replace_all(abstracts, "\\s+"," ")

```

```{r Create Data Frame}

database = data.frame(
  ID = ids,
  Title = titles,
  Journal = journal,
  Publication_Date= date,
  Abstract = abstracts
)

knitr::kable(database)

```